"""
Tenant and department management module.
"""

from .client import DepartmentClient, TenantClient
from .exceptions import (
    DepartmentCircularReferenceError,
    DepartmentCodeExistsError,
    DepartmentError,
    DepartmentHasChildrenError,
    DepartmentHasMembersError,
    DepartmentNotFoundError,
    SSOConfigError,
    SSOConfigNotFoundError,
    SSOConnectionError,
    SSOProviderError,
    TenantDomainExistsError,
    TenantError,
    TenantNotFoundError,
    TenantSlugExistsError,
)
from .models import (
    Address,
    AttributeMappings,
    AzureADConfig,
    BillingCycle,
    CreateDepartmentRequest,
    CreateTenantRequest,
    Department,
    DepartmentListResponse,
    DepartmentMembersResponse,
    DepartmentSummary,
    DepartmentTree,
    DepartmentWithDetails,
    GoogleConfig,
    JITProvisioningConfig,
    OIDCConfig,
    OktaConfig,
    Pagination,
    PrimaryContact,
    SAMLConfig,
    SCIMConfig,
    SSOConfig,
    SSOProvider,
    SSOSyncResult,
    SSOTestResult,
    SubscriptionPlan,
    SyncFrequency,
    Tenant,
    TenantFeatures,
    TenantListResponse,
    TenantStatus,
    TenantSummary,
    UpdateDepartmentRequest,
    UpdateSSOConfigRequest,
    UpdateTenantRequest,
    UserSummary,
)

__all__ = [
    # Clients
    "TenantClient",
    "DepartmentClient",
    # Exceptions
    "TenantError",
    "TenantNotFoundError",
    "TenantSlugExistsError",
    "TenantDomainExistsError",
    "SSOConfigError",
    "SSOConfigNotFoundError",
    "SSOConnectionError",
    "SSOProviderError",
    "DepartmentError",
    "DepartmentNotFoundError",
    "DepartmentCodeExistsError",
    "DepartmentHasMembersError",
    "DepartmentHasChildrenError",
    "DepartmentCircularReferenceError",
    # Enums
    "TenantStatus",
    "SubscriptionPlan",
    "BillingCycle",
    "SSOProvider",
    "SyncFrequency",
    # Models
    "Tenant",
    "TenantSummary",
    "TenantFeatures",
    "TenantListResponse",
    "PrimaryContact",
    "Address",
    "SSOConfig",
    "AzureADConfig",
    "OktaConfig",
    "GoogleConfig",
    "SAMLConfig",
    "OIDCConfig",
    "SCIMConfig",
    "JITProvisioningConfig",
    "AttributeMappings",
    "SSOTestResult",
    "SSOSyncResult",
    "Department",
    "DepartmentSummary",
    "DepartmentTree",
    "DepartmentWithDetails",
    "DepartmentListResponse",
    "DepartmentMembersResponse",
    "UserSummary",
    "Pagination",
    # Request models
    "CreateTenantRequest",
    "UpdateTenantRequest",
    "UpdateSSOConfigRequest",
    "CreateDepartmentRequest",
    "UpdateDepartmentRequest",
]
